SELECT SUM(populacao) FROM estado;
SELECT SUM(populacao) FROM cidade;
SELECT SUM(populacao) FROM estado WHERE fundacao > '1900-10-01';
SELECT SUM(populacao) FROM cidade WHERE fundacao > '2000-23-09';
SELECT SUM(populacao) FROM estado WHERE prefeito = 'Leonardo Pascoal';
SELECT SUM(populacao) FROM cidade WHERE prefeito = 'Ari Vequi';
SELECT SUM(populacao) FROM estado WHERE fundacao BETWEEN '1800-01-01' AND '1900-12-31';
SELECT SUM(populacao) FROM cidade WHERE fundacao BETWEEN '1950-01-01' AND '2000-12-31';
SELECT SUM(populacao) FROM estado WHERE estado = 'São Paulo';
SELECT SUM(populacao) FROM cidade WHERE cidade = 'Rio de Janeiro';
SELECT SUM(populacao) FROM estado WHERE prefeito = 'Beto Lunitti' AND fundacao < '1800-01-01';
SELECT SUM(populacao) FROM cidade WHERE prefeito = 'Paula Mascarenhas' AND fundacao > '1990-01-01';
SELECT SUM(populacao) FROM estado WHERE estado = 'Minas Gerais';
SELECT SUM(populacao) FROM cidade WHERE cidade = 'Salvador';
SELECT SUM(populacao) FROM estado WHERE prefeito IS NOT NULL;
SELECT SUM(populacao) FROM cidade WHERE prefeito IS NULL;
SELECT SUM(populacao) FROM estado WHERE populacao > 1000000;
SELECT SUM(populacao) FROM cidade WHERE populacao < 500000;
SELECT SUM(populacao) FROM estado WHERE fundacao < '1850-01-01';
SELECT SUM(populacao) FROM cidade WHERE fundacao > '1900-01-01';
