INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Roraima', 'Rorainopolis', '30782', '1992-05-05', 'Leila Lopes');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amapa', 'Santana', '122176', '1981-01-01', 'Bala Rocha');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Pernambuco', 'Olinda', '392482', '1535-03-12', 'Lupercio Nascimento');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Ceara', 'Juazeiro do Norte', '278264', '1911-07-22', 'Gledson Bezerra');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Bahia', 'Ilheus', '159923', '1534-06-28', 'Mario Alexandre');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Maranhao', 'Caxias', '164880', '1836-12-25', 'Fabio Gentil');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Rio Grande do Norte', 'Parnamirim', '272490', '1958-12-17', 'Rosano Taveira');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Paraiba', 'Patos', '108766', '1903-07-24', 'Nabor Wanderley');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Sergipe', 'Itabaiana', '96352', '1888-06-08', 'Adailton Sousa');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Alagoas', 'Penedo', '64611', '1535-04-12', 'Ronaldo Lopes');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Goias', 'Rio Verde', '241518', '1848-08-05', 'Paulo do Vale');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso', 'Lucas do Rio Verde', '69470', '1988-08-05', 'Miguel Vaz');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Bahia', 'Barreiras', '156975', '1891-05-26', 'Zito Barbosa');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amazonas', 'Coari', '84366', '1932-05-02', 'Adail Filho');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Para', 'Altamira', '115983', '1911-11-06', 'Claudio Furman');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Rondonia', 'Cacoal', '91819', '1977-11-26', 'Adailton Furia');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Maranhao', 'Timon', '170222', '1890-04-22', 'Dinair Veloso');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Pernambuco', 'Petrolina', '354317', '1893-09-21', 'Miguel Coelho');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Para', 'Castanhal', '202066', '1932-01-28', 'Paulo Titan');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Ceara', 'Maracanau', '229458', '1983-03-06', 'Roberto Pessoa');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Bahia', 'Alagoinhas', '154495', '1852-06-16', 'Joaquim Neto');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Piaui', 'Piripiri', '62063', '1910-04-04', 'Luis Menezes');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Paraiba', 'Bayeux', '99716', '1959-07-15', 'Luciene Gomes');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Roraima', 'Caracarai', '20920', '1935-09-17', 'Elvira Machado');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Goias', 'Senador Canedo', '121408', '1989-10-17', 'Fernando Pellozo');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso do Sul', 'Corumba', '112435', '1778-09-21', 'Marcelo Iunes');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Acre', 'Tarauaca', '43151', '1913-09-15', 'Marilete Vitorino');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Sergipe', 'Estancia', '69736', '1831-11-05', 'Gilson Andrade');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Maranhao', 'Bacabal', '104633', '1920-04-17', 'Edvan Brandao');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amazonas', 'Tabatinga', '67182', '1983-01-25', 'Saul Bemerguy');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Paraiba', 'Sousa', '69233', '1854-07-10', 'Fábio Tyrone');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Ceara', 'Caucaia', '368918', '1759-10-15', 'Vitor Valim');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Goias', 'Trindade', '131366', '1920-09-06', 'Marden Junior');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso', 'Primavera do Leste', '65704', '1986-05-13', 'Leonardo Bortolin');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Rondonia', 'Vilhena', '102211', '1977-11-23', 'Eduardo Japonês');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso do Sul', 'Ponta Pora', '95497', '1912-07-18', 'Helio Peluffo');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Bahia', 'Jequie', '156126', '1897-10-25', 'Zé Cocá');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Piaui', 'Floriano', '60884', '1897-07-08', 'Joel Rodrigues');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Tocantins', 'Porto Nacional', '53919', '1809-05-13', 'Ronivon Maciel');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Para', 'Parauapebas', '210770', '1988-05-10', 'Darci Lermen');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Alagoas', 'Palmeira dos Indios', '73024', '1822-08-20', 'Julio Cezar');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Roraima', 'Alto Alegre', '18917', '1995-05-20', 'Pedro Henrique');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Acre', 'Sena Madureira', '45451', '1904-09-25', 'Mazinho Serafim');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Ceara', 'Maranguape', '131625', '1851-08-17', 'Aline Albuquerque');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso', 'Cuiaba', '618124', '1719-04-08', 'Emanuel Pinheiro');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso do Sul', 'Campo Grande', '906092', '1899-08-26', 'Marcos Trad');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Goias', 'Goiania', '1536097', '1933-10-24', 'Rogerio Cruz');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Distrito Federal', 'Brasilia', '3149300', '1960-04-21', 'Ibaneis Rocha');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Bahia', 'Salvador', '2886698', '1549-03-29', 'Bruno Reis');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Ceara', 'Fortaleza', '2686612', '1726-04-13', 'Jose Sarto');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Pernambuco', 'Recife', '1667341', '1537-03-12', 'Joao Campos');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Para', 'Belem', '1501390', '1616-01-12', 'Edmilson Rodrigues');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amazonas', 'Manaus', '2327084', '1669-10-24', 'David Almeida');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Tocantins', 'Palmas', '313349', '1989-05-20', 'Cinthia Ribeiro');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Rondonia', 'Porto Velho', '539354', '1914-10-02', 'Hildon Chaves');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Acre', 'Rio Branco', '419452', '1882-12-28', 'Tiao Bocalom');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Roraima', 'Boa Vista', '436707', '1890-07-09', 'Arthur Henrique');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amapa', 'Macapa', '522357', '1758-02-04', 'Furlan');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Maranhao', 'Sao Luis', '1115932', '1612-09-08', 'Eduardo Braide');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Piaui', 'Teresina', '868075', '1852-08-16', 'Dr. Pessoa');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Rio Grande do Norte', 'Natal', '896708', '1599-12-25', 'Alvaro Dias');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Paraiba', 'Joao Pessoa', '817511', '1585-08-05', 'Cicero Lucena');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Sergipe', 'Aracaju', '672614', '1855-03-17', 'Edvaldo Nogueira');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Alagoas', 'Maceio', '1025360', '1815-12-05', 'JHC');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Bahia', 'Feira de Santana', '627477', '1833-09-18', 'Colbert Martins');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Goias', 'Anapolis', '391772', '1907-07-31', 'Roberto Naves');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso', 'Varzea Grande', '290383', '1867-05-15', 'Kalil Baracat');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso do Sul', 'Dourados', '225495', '1935-12-20', 'Alan Guedes');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Tocantins', 'Araguaina', '183381', '1958-11-14', 'Wagner Rodrigues');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Para', 'Santarem', '306480', '1758-06-22', 'Nelio Aguiar');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amazonas', 'Itacoatiara', '101337', '1683-09-08', 'Mario Abrahao');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Acre', 'Cruzeiro do Sul', '88376', '1904-09-28', 'Zezinho Barbary');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Ceara', 'Sobral', '210711', '1772-07-05', 'Ivo Gomes');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Bahia', 'Vitoria da Conquista', '343230', '1783-11-09', 'Sheila Lemos');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Pernambuco', 'Caruaru', '369120', '1849-05-18', 'Raquel Lyra');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Maranhao', 'Imperatriz', '259337', '1852-07-16', 'Assis Ramos');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Rio Grande do Norte', 'Mossoro', '303792', '1852-08-15', 'Alysson Bezerra');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Piaui', 'Parnaiba', '153482', '1761-07-14', 'Mao Santa');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Paraiba', 'Campina Grande', '414421', '1864-10-11', 'Bruno Cunha Lima');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Sergipe', 'Nossa Senhora do Socorro', '186403', '1868-05-12', 'Padre Inaldo');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Alagoas', 'Arapiraca', '233047', '1924-10-30', 'Luciano Barbosa');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso', 'Rondonopolis', '241518', '1953-12-10', 'Jose Carlos do Patio');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Goias', 'Aparecida de Goiania', '601844', '1922-11-11', 'Gustavo Mendanha');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Mato Grosso do Sul', 'Tres Lagoas', '123281', '1915-06-15', 'Angelo Guerreiro');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Tocantins', 'Gurupi', '87233', '1958-10-14', 'Josi Nunes');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Para', 'Maraba', '283542', '1913-04-05', 'Tiao Miranda');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amazonas', 'Parintins', '113168', '1796-10-15', 'Bi Garcia');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Rondonia', 'Ji-Parana', '131026', '1977-04-22', 'Isau Fonseca');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amapa', 'Oiapoque', '26312', '1945-05-15', 'Maria Orlanda');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Pernambuco', 'Garanhuns', '140577', '1879-03-10', 'Silvino Duarte');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Ceara', 'Iguatu', '104142', '1859-07-27', 'Ednaldo Lavor');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Bahia', 'Jacobina', '82515', '1880-09-28', 'Tiago Dias');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Maranhao', 'Balsas', '94779', '1918-12-22', 'Erivelton Neves');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Goias', 'Formosa', '120356', '1843-08-01', 'Gustavo Marques');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Para', 'Braganca', '129521', '1613-07-16', 'Raimundo Oliveira');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Amazonas', 'Manacapuru', '98615', '1865-04-16', 'Beto Dangelo');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Piaui', 'Campo Maior', '46053', '1762-08-08', 'Joaozinho Felix');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Tocantins', 'Colinas do Tocantins', '35860', '1961-09-19', 'Adriano Rabelo');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Alagoas', 'Delmiro Gouveia', '53508', '1952-05-12', 'Ziane Costa');
INSERT INTO cidades_brasil (estado, cidade, populacao, fundacao, prefeito) VALUES ('Rondonia', 'Ariquemes', '107863', '1977-10-11', 'Carla Redano');

DELETE FROM cidades_brasil WHERE cidade = 'Rorainopolis';
DELETE FROM cidades_brasil WHERE estado = 'Tocantins';
DELETE FROM cidades_brasil WHERE fundacao < '1900-01-01';
DELETE FROM cidades_brasil WHERE populacao < 50000;
DELETE FROM cidades_brasil WHERE cidade LIKE 'B%';
DELETE FROM cidades_brasil WHERE fundacao BETWEEN '1850-01-01' AND '1900-12-31';
DELETE FROM cidades_brasil WHERE populacao = (SELECT MIN(populacao) FROM cidades_brasil);
DELETE FROM cidades_brasil WHERE cidade = 'Recife';
DELETE FROM cidades_brasil WHERE estado NOT IN ('Bahia', 'Ceara');
DELETE FROM cidades_brasil WHERE populacao BETWEEN 60000 AND 70000;
DELETE FROM cidades_brasil WHERE cidade = 'Juazeiro do Norte';
DELETE FROM cidades_brasil WHERE cidade = 'Olinda';
DELETE FROM cidades_brasil WHERE cidade = 'Santana';
DELETE FROM cidades_brasil WHERE cidade = 'Ilheus';
DELETE FROM cidades_brasil WHERE cidade = 'Caxias';
DELETE FROM cidades_brasil WHERE cidade = 'Parnamirim';
DELETE FROM cidades_brasil WHERE cidade = 'Patos';
DELETE FROM cidades_brasil WHERE cidade = 'Itabaiana';
DELETE FROM cidades_brasil WHERE cidade = 'Penedo';
DELETE FROM cidades_brasil WHERE cidade = 'Rio Verde';
DELETE FROM cidades_brasil WHERE cidade = 'Lucas do Rio Verde';
DELETE FROM cidades_brasil WHERE cidade = 'Barreiras';
DELETE FROM cidades_brasil WHERE cidade = 'Coari';
DELETE FROM cidades_brasil WHERE cidade = 'Altamira';
DELETE FROM cidades_brasil WHERE cidade = 'Cacoal';
DELETE FROM cidades_brasil WHERE cidade = 'Timon';
DELETE FROM cidades_brasil WHERE cidade = 'Petrolina';
DELETE FROM cidades_brasil WHERE cidade = 'Castanhal';
DELETE FROM cidades_brasil WHERE cidade = 'Maracanau';
DELETE FROM cidades_brasil WHERE cidade = 'Alagoinhas';
DELETE FROM cidades_brasil WHERE estado = 'Maranhao';